connect 'jdbc:derby:C:\Users\rahul\OneDrive\Desktop\workshop\temp\wdg_inspect\database';
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'CUSTOMER','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\customers.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'WORKSHEET','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\worksheets.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'INVOICE_ITEM','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\invoice_items.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'INVOICE','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\invoices.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'ITEM','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\parts.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'MASTER_ITEM','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\master_items.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'THING','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\vehicles.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'PROBLEM','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\problems.csv',',','"','UTF-8');
CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE(null,'ADDRESS','C:\Users\rahul\OneDrive\Desktop\workshop\temp\derby_export\addresses.csv',',','"','UTF-8');
exit;