CONNECT 'jdbc:derby:C:/Users/rahul/OneDrive/Desktop/workshop-solo/scratch/DB_copy';
DESCRIBE CUSTOMER;
DESCRIBE WORKSHEET;
DESCRIBE INVOICE;
DESCRIBE ITEM;
DESCRIBE PROBLEM;
DESCRIBE THING;
DESCRIBE MASTER_ITEM;
